#!/usr/bin/env python3
"""Assemble the Orion app:
   1) src/* -> index.html (self-contained static bundle served by Express)
   2) src/questions.js -> server/data/questions.cjs (seeded into MongoDB)
"""
import pathlib, re

SRC = pathlib.Path(__file__).resolve().parent.parent / "src"
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_HTML = ROOT / "index.html"
OUT_DATA = ROOT / "server" / "data" / "questions.cjs"

def read(name):
    return (SRC / name).read_text(encoding="utf-8")

# 1. static bundle
css = read("styles.css")
app = "".join(read(p) for p in [
    "app-core.js",
    "app-api.js",
    "app-console.js",
    "app-candidate.js",
    "app-org.js",
    "app-init.js",
])

html = read("shell.html")
html = html.replace("/*__CSS__*/", css)
html = html.replace("/*__APP__*/", app)
OUT_HTML.write_text(html, encoding="utf-8")

# 2. CommonJS data file for the server seed
qs_src = read("questions.js")
m = re.search(r"const BUILTIN_QUESTIONS = \[([\s\S]*?)\n\];", qs_src)
if not m:
    raise SystemExit("could not find BUILTIN_QUESTIONS array in questions.js")
OUT_DATA.parent.mkdir(parents=True, exist_ok=True)
OUT_DATA.write_text(
    "// Generated by tools/build.py — do not edit.\n"
    "'use strict';\n"
    "const BUILTIN_QUESTIONS = [" + m.group(1) + "\n];\n"
    "module.exports = BUILTIN_QUESTIONS;\n",
    encoding="utf-8",
)

print(f"Built {OUT_HTML} ({OUT_HTML.stat().st_size:,} bytes)")
print(f"Built {OUT_DATA} ({OUT_DATA.stat().st_size:,} bytes)")
